apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapetanios
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kapetanios
subjects:
  - kind: ServiceAccount
    name: kapetanios
    namespace: default