apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapetanios
  namespace: default
  labels:
    name: kapetanios
spec:
  selector:
    matchLabels:
      app: kapetanios
  template:
    metadata:
      labels:
        app: kapetanios
    spec:
      containers:
# TO-DO:
        - image: quay.io/klovercloud/kapetanios:latest
          imagePullPolicy: Always
          name: kapetanios
      terminationGracePeriodSeconds: 60
      schedulerName: default-scheduler
      serviceAccountName: kapetanios