apiVersion: v1
kind: Service
metadata:
  name: kapetanios
  labels:
    app: kapetanios
spec:
  selector:
    app: kapetanios
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: kapetanios
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: kapetanios-grpc
  type: ClusterIP