// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: proto/certs-expiration.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Validity_ClusterHealthChecking_FullMethodName = "/Validity/ClusterHealthChecking"
	Validity_ExpirationInfo_FullMethodName        = "/Validity/ExpirationInfo"
)

// ValidityClient is the client API for Validity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidityClient interface {
	ClusterHealthChecking(ctx context.Context, in *PrerequisitesExpiration, opts ...grpc.CallOption) (*CertificateValidityResponse, error)
	ExpirationInfo(ctx context.Context, in *Expiration, opts ...grpc.CallOption) (*CertificateValidityResponse, error)
}

type validityClient struct {
	cc grpc.ClientConnInterface
}

func NewValidityClient(cc grpc.ClientConnInterface) ValidityClient {
	return &validityClient{cc}
}

func (c *validityClient) ClusterHealthChecking(ctx context.Context, in *PrerequisitesExpiration, opts ...grpc.CallOption) (*CertificateValidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateValidityResponse)
	err := c.cc.Invoke(ctx, Validity_ClusterHealthChecking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validityClient) ExpirationInfo(ctx context.Context, in *Expiration, opts ...grpc.CallOption) (*CertificateValidityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateValidityResponse)
	err := c.cc.Invoke(ctx, Validity_ExpirationInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidityServer is the server API for Validity service.
// All implementations must embed UnimplementedValidityServer
// for forward compatibility.
type ValidityServer interface {
	ClusterHealthChecking(context.Context, *PrerequisitesExpiration) (*CertificateValidityResponse, error)
	ExpirationInfo(context.Context, *Expiration) (*CertificateValidityResponse, error)
	mustEmbedUnimplementedValidityServer()
}

// UnimplementedValidityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidityServer struct{}

func (UnimplementedValidityServer) ClusterHealthChecking(context.Context, *PrerequisitesExpiration) (*CertificateValidityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterHealthChecking not implemented")
}
func (UnimplementedValidityServer) ExpirationInfo(context.Context, *Expiration) (*CertificateValidityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpirationInfo not implemented")
}
func (UnimplementedValidityServer) mustEmbedUnimplementedValidityServer() {}
func (UnimplementedValidityServer) testEmbeddedByValue()                  {}

// UnsafeValidityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidityServer will
// result in compilation errors.
type UnsafeValidityServer interface {
	mustEmbedUnimplementedValidityServer()
}

func RegisterValidityServer(s grpc.ServiceRegistrar, srv ValidityServer) {
	// If the following call pancis, it indicates UnimplementedValidityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Validity_ServiceDesc, srv)
}

func _Validity_ClusterHealthChecking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrerequisitesExpiration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidityServer).ClusterHealthChecking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Validity_ClusterHealthChecking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidityServer).ClusterHealthChecking(ctx, req.(*PrerequisitesExpiration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Validity_ExpirationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Expiration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidityServer).ExpirationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Validity_ExpirationInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidityServer).ExpirationInfo(ctx, req.(*Expiration))
	}
	return interceptor(ctx, in, info, handler)
}

// Validity_ServiceDesc is the grpc.ServiceDesc for Validity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Validity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Validity",
	HandlerType: (*ValidityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterHealthChecking",
			Handler:    _Validity_ClusterHealthChecking_Handler,
		},
		{
			MethodName: "ExpirationInfo",
			Handler:    _Validity_ExpirationInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/certs-expiration.proto",
}
