// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: proto/cert-renewal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// PrerequisitesClient is the client API for Prerequisites service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrerequisitesClient interface {
}

type prerequisitesClient struct {
	cc grpc.ClientConnInterface
}

func NewPrerequisitesClient(cc grpc.ClientConnInterface) PrerequisitesClient {
	return &prerequisitesClient{cc}
}

// PrerequisitesServer is the server API for Prerequisites service.
// All implementations must embed UnimplementedPrerequisitesServer
// for forward compatibility.
type PrerequisitesServer interface {
	mustEmbedUnimplementedPrerequisitesServer()
}

// UnimplementedPrerequisitesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrerequisitesServer struct{}

func (UnimplementedPrerequisitesServer) mustEmbedUnimplementedPrerequisitesServer() {}
func (UnimplementedPrerequisitesServer) testEmbeddedByValue()                       {}

// UnsafePrerequisitesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrerequisitesServer will
// result in compilation errors.
type UnsafePrerequisitesServer interface {
	mustEmbedUnimplementedPrerequisitesServer()
}

func RegisterPrerequisitesServer(s grpc.ServiceRegistrar, srv PrerequisitesServer) {
	// If the following call pancis, it indicates UnimplementedPrerequisitesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Prerequisites_ServiceDesc, srv)
}

// Prerequisites_ServiceDesc is the grpc.ServiceDesc for Prerequisites service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Prerequisites_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Prerequisites",
	HandlerType: (*PrerequisitesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/cert-renewal.proto",
}

const (
	Backup_ClusterHealthChecking_FullMethodName = "/Backup/ClusterHealthChecking"
)

// BackupClient is the client API for Backup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupClient interface {
	ClusterHealthChecking(ctx context.Context, in *PrerequisiteCheckReport, opts ...grpc.CallOption) (*CreateResponse, error)
}

type backupClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupClient(cc grpc.ClientConnInterface) BackupClient {
	return &backupClient{cc}
}

func (c *backupClient) ClusterHealthChecking(ctx context.Context, in *PrerequisiteCheckReport, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Backup_ClusterHealthChecking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServer is the server API for Backup service.
// All implementations must embed UnimplementedBackupServer
// for forward compatibility.
type BackupServer interface {
	ClusterHealthChecking(context.Context, *PrerequisiteCheckReport) (*CreateResponse, error)
	mustEmbedUnimplementedBackupServer()
}

// UnimplementedBackupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupServer struct{}

func (UnimplementedBackupServer) ClusterHealthChecking(context.Context, *PrerequisiteCheckReport) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterHealthChecking not implemented")
}
func (UnimplementedBackupServer) mustEmbedUnimplementedBackupServer() {}
func (UnimplementedBackupServer) testEmbeddedByValue()                {}

// UnsafeBackupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServer will
// result in compilation errors.
type UnsafeBackupServer interface {
	mustEmbedUnimplementedBackupServer()
}

func RegisterBackupServer(s grpc.ServiceRegistrar, srv BackupServer) {
	// If the following call pancis, it indicates UnimplementedBackupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Backup_ServiceDesc, srv)
}

func _Backup_ClusterHealthChecking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrerequisiteCheckReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServer).ClusterHealthChecking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Backup_ClusterHealthChecking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServer).ClusterHealthChecking(ctx, req.(*PrerequisiteCheckReport))
	}
	return interceptor(ctx, in, info, handler)
}

// Backup_ServiceDesc is the grpc.ServiceDesc for Backup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Backup",
	HandlerType: (*BackupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterHealthChecking",
			Handler:    _Backup_ClusterHealthChecking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cert-renewal.proto",
}

const (
	Renewal_ClusterHealthChecking_FullMethodName = "/Renewal/ClusterHealthChecking"
	Renewal_BackupUpdate_FullMethodName          = "/Renewal/BackupUpdate"
	Renewal_StatusUpdate_FullMethodName          = "/Renewal/StatusUpdate"
)

// RenewalClient is the client API for Renewal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RenewalClient interface {
	ClusterHealthChecking(ctx context.Context, in *PrerequisiteCheckReport, opts ...grpc.CallOption) (*CreateResponse, error)
	BackupUpdate(ctx context.Context, in *BackupStatus, opts ...grpc.CallOption) (*CreateResponse, error)
	StatusUpdate(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type renewalClient struct {
	cc grpc.ClientConnInterface
}

func NewRenewalClient(cc grpc.ClientConnInterface) RenewalClient {
	return &renewalClient{cc}
}

func (c *renewalClient) ClusterHealthChecking(ctx context.Context, in *PrerequisiteCheckReport, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Renewal_ClusterHealthChecking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *renewalClient) BackupUpdate(ctx context.Context, in *BackupStatus, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Renewal_BackupUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *renewalClient) StatusUpdate(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Renewal_StatusUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RenewalServer is the server API for Renewal service.
// All implementations must embed UnimplementedRenewalServer
// for forward compatibility.
type RenewalServer interface {
	ClusterHealthChecking(context.Context, *PrerequisiteCheckReport) (*CreateResponse, error)
	BackupUpdate(context.Context, *BackupStatus) (*CreateResponse, error)
	StatusUpdate(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedRenewalServer()
}

// UnimplementedRenewalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRenewalServer struct{}

func (UnimplementedRenewalServer) ClusterHealthChecking(context.Context, *PrerequisiteCheckReport) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterHealthChecking not implemented")
}
func (UnimplementedRenewalServer) BackupUpdate(context.Context, *BackupStatus) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupUpdate not implemented")
}
func (UnimplementedRenewalServer) StatusUpdate(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusUpdate not implemented")
}
func (UnimplementedRenewalServer) mustEmbedUnimplementedRenewalServer() {}
func (UnimplementedRenewalServer) testEmbeddedByValue()                 {}

// UnsafeRenewalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RenewalServer will
// result in compilation errors.
type UnsafeRenewalServer interface {
	mustEmbedUnimplementedRenewalServer()
}

func RegisterRenewalServer(s grpc.ServiceRegistrar, srv RenewalServer) {
	// If the following call pancis, it indicates UnimplementedRenewalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Renewal_ServiceDesc, srv)
}

func _Renewal_ClusterHealthChecking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrerequisiteCheckReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenewalServer).ClusterHealthChecking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Renewal_ClusterHealthChecking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenewalServer).ClusterHealthChecking(ctx, req.(*PrerequisiteCheckReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Renewal_BackupUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenewalServer).BackupUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Renewal_BackupUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenewalServer).BackupUpdate(ctx, req.(*BackupStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _Renewal_StatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenewalServer).StatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Renewal_StatusUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenewalServer).StatusUpdate(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Renewal_ServiceDesc is the grpc.ServiceDesc for Renewal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Renewal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Renewal",
	HandlerType: (*RenewalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterHealthChecking",
			Handler:    _Renewal_ClusterHealthChecking_Handler,
		},
		{
			MethodName: "BackupUpdate",
			Handler:    _Renewal_BackupUpdate_Handler,
		},
		{
			MethodName: "StatusUpdate",
			Handler:    _Renewal_StatusUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cert-renewal.proto",
}
