// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: proto/minor-upgrade.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MinorUpgrade_ClusterHealthChecking_FullMethodName   = "/MinorUpgrade/ClusterHealthChecking"
	MinorUpgrade_UpgradeVersionSelection_FullMethodName = "/MinorUpgrade/UpgradeVersionSelection"
	MinorUpgrade_ClusterCompatibility_FullMethodName    = "/MinorUpgrade/ClusterCompatibility"
	MinorUpgrade_ClusterComponentUpgrade_FullMethodName = "/MinorUpgrade/ClusterComponentUpgrade"
	MinorUpgrade_ClusterUpgradePlan_FullMethodName      = "/MinorUpgrade/ClusterUpgradePlan"
	MinorUpgrade_ClusterUpgrade_FullMethodName          = "/MinorUpgrade/ClusterUpgrade"
	MinorUpgrade_ClusterComponentRestart_FullMethodName = "/MinorUpgrade/ClusterComponentRestart"
)

// MinorUpgradeClient is the client API for MinorUpgrade service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinorUpgradeClient interface {
	ClusterHealthChecking(ctx context.Context, in *PrerequisitesMinorUpgrade, opts ...grpc.CallOption) (*UpgradeResponse, error)
	UpgradeVersionSelection(ctx context.Context, in *AvailableVersions, opts ...grpc.CallOption) (*ClusterUpgradeResponse, error)
	ClusterCompatibility(ctx context.Context, in *UpgradeCompatibility, opts ...grpc.CallOption) (*UpgradeResponse, error)
	ClusterComponentUpgrade(ctx context.Context, in *ComponentUpgradeStatus, opts ...grpc.CallOption) (*UpgradeResponse, error)
	ClusterUpgradePlan(ctx context.Context, in *UpgradePlan, opts ...grpc.CallOption) (*UpgradeResponse, error)
	ClusterUpgrade(ctx context.Context, in *UpgradeStatus, opts ...grpc.CallOption) (*UpgradeResponse, error)
	ClusterComponentRestart(ctx context.Context, in *ComponentRestartStatus, opts ...grpc.CallOption) (*UpgradeResponse, error)
}

type minorUpgradeClient struct {
	cc grpc.ClientConnInterface
}

func NewMinorUpgradeClient(cc grpc.ClientConnInterface) MinorUpgradeClient {
	return &minorUpgradeClient{cc}
}

func (c *minorUpgradeClient) ClusterHealthChecking(ctx context.Context, in *PrerequisitesMinorUpgrade, opts ...grpc.CallOption) (*UpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeResponse)
	err := c.cc.Invoke(ctx, MinorUpgrade_ClusterHealthChecking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minorUpgradeClient) UpgradeVersionSelection(ctx context.Context, in *AvailableVersions, opts ...grpc.CallOption) (*ClusterUpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterUpgradeResponse)
	err := c.cc.Invoke(ctx, MinorUpgrade_UpgradeVersionSelection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minorUpgradeClient) ClusterCompatibility(ctx context.Context, in *UpgradeCompatibility, opts ...grpc.CallOption) (*UpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeResponse)
	err := c.cc.Invoke(ctx, MinorUpgrade_ClusterCompatibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minorUpgradeClient) ClusterComponentUpgrade(ctx context.Context, in *ComponentUpgradeStatus, opts ...grpc.CallOption) (*UpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeResponse)
	err := c.cc.Invoke(ctx, MinorUpgrade_ClusterComponentUpgrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minorUpgradeClient) ClusterUpgradePlan(ctx context.Context, in *UpgradePlan, opts ...grpc.CallOption) (*UpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeResponse)
	err := c.cc.Invoke(ctx, MinorUpgrade_ClusterUpgradePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minorUpgradeClient) ClusterUpgrade(ctx context.Context, in *UpgradeStatus, opts ...grpc.CallOption) (*UpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeResponse)
	err := c.cc.Invoke(ctx, MinorUpgrade_ClusterUpgrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minorUpgradeClient) ClusterComponentRestart(ctx context.Context, in *ComponentRestartStatus, opts ...grpc.CallOption) (*UpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeResponse)
	err := c.cc.Invoke(ctx, MinorUpgrade_ClusterComponentRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinorUpgradeServer is the server API for MinorUpgrade service.
// All implementations must embed UnimplementedMinorUpgradeServer
// for forward compatibility.
type MinorUpgradeServer interface {
	ClusterHealthChecking(context.Context, *PrerequisitesMinorUpgrade) (*UpgradeResponse, error)
	UpgradeVersionSelection(context.Context, *AvailableVersions) (*ClusterUpgradeResponse, error)
	ClusterCompatibility(context.Context, *UpgradeCompatibility) (*UpgradeResponse, error)
	ClusterComponentUpgrade(context.Context, *ComponentUpgradeStatus) (*UpgradeResponse, error)
	ClusterUpgradePlan(context.Context, *UpgradePlan) (*UpgradeResponse, error)
	ClusterUpgrade(context.Context, *UpgradeStatus) (*UpgradeResponse, error)
	ClusterComponentRestart(context.Context, *ComponentRestartStatus) (*UpgradeResponse, error)
	mustEmbedUnimplementedMinorUpgradeServer()
}

// UnimplementedMinorUpgradeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinorUpgradeServer struct{}

func (UnimplementedMinorUpgradeServer) ClusterHealthChecking(context.Context, *PrerequisitesMinorUpgrade) (*UpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterHealthChecking not implemented")
}
func (UnimplementedMinorUpgradeServer) UpgradeVersionSelection(context.Context, *AvailableVersions) (*ClusterUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeVersionSelection not implemented")
}
func (UnimplementedMinorUpgradeServer) ClusterCompatibility(context.Context, *UpgradeCompatibility) (*UpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterCompatibility not implemented")
}
func (UnimplementedMinorUpgradeServer) ClusterComponentUpgrade(context.Context, *ComponentUpgradeStatus) (*UpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterComponentUpgrade not implemented")
}
func (UnimplementedMinorUpgradeServer) ClusterUpgradePlan(context.Context, *UpgradePlan) (*UpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterUpgradePlan not implemented")
}
func (UnimplementedMinorUpgradeServer) ClusterUpgrade(context.Context, *UpgradeStatus) (*UpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterUpgrade not implemented")
}
func (UnimplementedMinorUpgradeServer) ClusterComponentRestart(context.Context, *ComponentRestartStatus) (*UpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterComponentRestart not implemented")
}
func (UnimplementedMinorUpgradeServer) mustEmbedUnimplementedMinorUpgradeServer() {}
func (UnimplementedMinorUpgradeServer) testEmbeddedByValue()                      {}

// UnsafeMinorUpgradeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinorUpgradeServer will
// result in compilation errors.
type UnsafeMinorUpgradeServer interface {
	mustEmbedUnimplementedMinorUpgradeServer()
}

func RegisterMinorUpgradeServer(s grpc.ServiceRegistrar, srv MinorUpgradeServer) {
	// If the following call pancis, it indicates UnimplementedMinorUpgradeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MinorUpgrade_ServiceDesc, srv)
}

func _MinorUpgrade_ClusterHealthChecking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrerequisitesMinorUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinorUpgradeServer).ClusterHealthChecking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinorUpgrade_ClusterHealthChecking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinorUpgradeServer).ClusterHealthChecking(ctx, req.(*PrerequisitesMinorUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinorUpgrade_UpgradeVersionSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableVersions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinorUpgradeServer).UpgradeVersionSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinorUpgrade_UpgradeVersionSelection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinorUpgradeServer).UpgradeVersionSelection(ctx, req.(*AvailableVersions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinorUpgrade_ClusterCompatibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeCompatibility)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinorUpgradeServer).ClusterCompatibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinorUpgrade_ClusterCompatibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinorUpgradeServer).ClusterCompatibility(ctx, req.(*UpgradeCompatibility))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinorUpgrade_ClusterComponentUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComponentUpgradeStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinorUpgradeServer).ClusterComponentUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinorUpgrade_ClusterComponentUpgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinorUpgradeServer).ClusterComponentUpgrade(ctx, req.(*ComponentUpgradeStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinorUpgrade_ClusterUpgradePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradePlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinorUpgradeServer).ClusterUpgradePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinorUpgrade_ClusterUpgradePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinorUpgradeServer).ClusterUpgradePlan(ctx, req.(*UpgradePlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinorUpgrade_ClusterUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinorUpgradeServer).ClusterUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinorUpgrade_ClusterUpgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinorUpgradeServer).ClusterUpgrade(ctx, req.(*UpgradeStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinorUpgrade_ClusterComponentRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComponentRestartStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinorUpgradeServer).ClusterComponentRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinorUpgrade_ClusterComponentRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinorUpgradeServer).ClusterComponentRestart(ctx, req.(*ComponentRestartStatus))
	}
	return interceptor(ctx, in, info, handler)
}

// MinorUpgrade_ServiceDesc is the grpc.ServiceDesc for MinorUpgrade service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinorUpgrade_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MinorUpgrade",
	HandlerType: (*MinorUpgradeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterHealthChecking",
			Handler:    _MinorUpgrade_ClusterHealthChecking_Handler,
		},
		{
			MethodName: "UpgradeVersionSelection",
			Handler:    _MinorUpgrade_UpgradeVersionSelection_Handler,
		},
		{
			MethodName: "ClusterCompatibility",
			Handler:    _MinorUpgrade_ClusterCompatibility_Handler,
		},
		{
			MethodName: "ClusterComponentUpgrade",
			Handler:    _MinorUpgrade_ClusterComponentUpgrade_Handler,
		},
		{
			MethodName: "ClusterUpgradePlan",
			Handler:    _MinorUpgrade_ClusterUpgradePlan_Handler,
		},
		{
			MethodName: "ClusterUpgrade",
			Handler:    _MinorUpgrade_ClusterUpgrade_Handler,
		},
		{
			MethodName: "ClusterComponentRestart",
			Handler:    _MinorUpgrade_ClusterComponentRestart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/minor-upgrade.proto",
}
