// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: proto/minor-upgrade.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MinorUpgrade_ClusterHealthChecking_FullMethodName = "/MinorUpgrade/ClusterHealthChecking"
)

// MinorUpgradeClient is the client API for MinorUpgrade service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinorUpgradeClient interface {
	ClusterHealthChecking(ctx context.Context, in *PrerequisitesMinorUpgrade, opts ...grpc.CallOption) (*CreateUpgradeResponse, error)
}

type minorUpgradeClient struct {
	cc grpc.ClientConnInterface
}

func NewMinorUpgradeClient(cc grpc.ClientConnInterface) MinorUpgradeClient {
	return &minorUpgradeClient{cc}
}

func (c *minorUpgradeClient) ClusterHealthChecking(ctx context.Context, in *PrerequisitesMinorUpgrade, opts ...grpc.CallOption) (*CreateUpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUpgradeResponse)
	err := c.cc.Invoke(ctx, MinorUpgrade_ClusterHealthChecking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinorUpgradeServer is the server API for MinorUpgrade service.
// All implementations must embed UnimplementedMinorUpgradeServer
// for forward compatibility.
type MinorUpgradeServer interface {
	ClusterHealthChecking(context.Context, *PrerequisitesMinorUpgrade) (*CreateUpgradeResponse, error)
	mustEmbedUnimplementedMinorUpgradeServer()
}

// UnimplementedMinorUpgradeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinorUpgradeServer struct{}

func (UnimplementedMinorUpgradeServer) ClusterHealthChecking(context.Context, *PrerequisitesMinorUpgrade) (*CreateUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterHealthChecking not implemented")
}
func (UnimplementedMinorUpgradeServer) mustEmbedUnimplementedMinorUpgradeServer() {}
func (UnimplementedMinorUpgradeServer) testEmbeddedByValue()                      {}

// UnsafeMinorUpgradeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinorUpgradeServer will
// result in compilation errors.
type UnsafeMinorUpgradeServer interface {
	mustEmbedUnimplementedMinorUpgradeServer()
}

func RegisterMinorUpgradeServer(s grpc.ServiceRegistrar, srv MinorUpgradeServer) {
	// If the following call pancis, it indicates UnimplementedMinorUpgradeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MinorUpgrade_ServiceDesc, srv)
}

func _MinorUpgrade_ClusterHealthChecking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrerequisitesMinorUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinorUpgradeServer).ClusterHealthChecking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinorUpgrade_ClusterHealthChecking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinorUpgradeServer).ClusterHealthChecking(ctx, req.(*PrerequisitesMinorUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

// MinorUpgrade_ServiceDesc is the grpc.ServiceDesc for MinorUpgrade service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinorUpgrade_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MinorUpgrade",
	HandlerType: (*MinorUpgradeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterHealthChecking",
			Handler:    _MinorUpgrade_ClusterHealthChecking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/minor-upgrade.proto",
}
